Repository moa-moa-service/moamoa-frontend, pull requests merged in 2024-02, with the labels that each got.

#28 feat: 검색페이지 퍼블리싱
  public/SearchPage/angle_left.png
  public/SearchPage/angle_right.png
  src/App.jsx
  src/app/SearchPage/SearchPage.main.jsx
  src/app/SearchPage/SearchPage.search.filter.category.jsx
  src/app/SearchPage/SearchPage.search.filter.period.jsx
  src/app/SearchPage/SearchPage.search.filter.price.jsx
  src/app/SearchPage/SearchPage.search.filter.quantity.jsx
  src/app/SearchPage/SearchPage.search.jsx
  src/app/SearchPage/styled/SearchPage.component.style.js
  src/app/SearchPage/styled/SearchPage.main.style.js
  src/app/SearchPage/styled/SearchPage.search.filter.category.style.js
  src/app/SearchPage/styled/SearchPage.search.filter.period.style.js
  src/app/SearchPage/styled/SearchPage.search.filter.price.style.js
  src/app/SearchPage/styled/SearchPage.search.filter.quantity.style.js
  src/app/SearchPage/styled/SearchPage.search.filter.style.js
  src/app/SearchPage/styled/SearchPage.search.style.js
Labels: enhancement

#32 feat: 공지사항 페이지 퍼블리싱
  public/NoticePage/moreIcon.png
  src/App.jsx
  src/app/NoticePage/NoticePage.notice.comment.jsx
  src/app/NoticePage/NoticePage.notice.jsx
  src/app/NoticePage/NoticePage.write.jsx
  src/app/NoticePage/styled/NoticePage.component.style.js
  src/app/NoticePage/styled/NoticePage.notice.comment.style.js
  src/app/NoticePage/styled/NoticePage.notice.style.js
  src/app/NoticePage/styled/NoticePage.write.style.js
  src/app/ProductPage/ProductPage.main.info.jsx
  src/app/ProductPage/ProductPage.main.info.notice.jsx
  src/app/ProductPage/ProductPage.main.jsx
  src/app/ProductPage/styled/ProductPage.main.info.notice.style.js
  src/app/ProductPage/styled/ProductPage.main.info.style.js
  src/app/ProductPage/styled/ProductPage.main.style.js
Labels: enhancement

#33 Feat/25
  package-lock.json
  package.json
  src/app/RecruitmentPage/Recruitment.MyMap.jsx
  src/setupProxy.js
Labels: enhancement

#36 Feat: 모집하기 내 네이버 지도 api 기능 구현
  index.html
  src/App.jsx
  src/app/MainPage/MainPage.CategoryDetailPage.jsx
  src/app/MainPage/MainPage.main.CategoryList.Category.jsx
  src/app/MenuNav/MenuNav.main.jsx
  src/app/RecruitmentPage/Recruitment.MyMap.jsx
  src/app/RecruitmentPage/Recruitment.TradingLocation.jsx
  src/app/RecruitmentPage/Recruitment.main.jsx
  src/app/SearchPage/SearchPage.main.jsx
Labels: bug, enhancement

#39 feat: 알림 페이지 퍼블리싱 & 컴포넌트 반응형 수정
  src/App.jsx
  src/app/MainPage/MainPage.Alarm.AlarmWrapper.jsx
  src/app/MainPage/MainPage.Alarm.jsx
  src/app/MainPage/MainPage.main.jsx
  src/app/MainPage/styled/MainPage.Alarm.style.js
  src/app/MainPage/styled/MainPage.CategoryDatailPage.style.js
  src/app/MainPage/styled/MainPage.CategoryDetailPage.Item.style.js
  src/app/MainPage/styled/MainPage.main.CategoryList.Category.style.js
  src/app/MainPage/styled/MainPage.main.CategoryList.style.js
  src/app/RecruitmentPage/styled/Recruitment.main.style.js
  src/app/SearchPage/styled/SearchPage.component.style.js
Labels: enhancement

#41 feat: 상품페이지 버튼 기능 구현
  src/App.jsx
  src/app/ProductPage/ProductPage.main.copyLinkModal.jsx
  src/app/ProductPage/ProductPage.main.imgModal.jsx
  src/app/ProductPage/ProductPage.main.jsx
  src/app/ProductPage/ProductPage.main.quantityModal.jsx
  src/app/ProductPage/styled/ProductPage.main.imgModal.style.js
Labels: enhancement

#43 feat: 모집하기 이미지 첨부 퍼블리싱 및 갤러리 호출
  src/app/RecruitmentPage/Recruitment.main.jsx
  src/app/RecruitmentPage/styled/Recruitment.main.style.js
Labels: enhancement

#45 Feat/44 로그인 > 우리 동네 설정 동네 이름 받아오기
  src/App.jsx
  src/app/LoginPage/LoginPage.main.AddressSetup.jsx
  src/app/RecruitmentPage/Recruitment.MyMap.jsx
  src/app/RecruitmentPage/Recruitment.TradingLocation.jsx
Labels: enhancement

#48 Feat/46 우리동네 페이지 퍼블리싱
  src/App.jsx
  src/app/LoginPage/LoginPage.main.AddressSetup.jsx
  src/app/MenuNav/MenuNav.main.jsx
  src/app/MyTownPage/MyTownPage.main.jsx
  src/app/MyTownPage/styled/MyTownPage.main.style.js
  src/app/RecruitmentPage/styled/Recruitment.TradingLocation.style.js
Labels: enhancement

#47 feat: 검색페이지 버튼 기능 구현
  package-lock.json
  package.json
  src/app/SearchPage/SearchPage.main.jsx
  src/app/SearchPage/SearchPage.search.filter.category.jsx
  src/app/SearchPage/SearchPage.search.filter.period.jsx
  src/app/SearchPage/SearchPage.search.filter.price.jsx
  src/app/SearchPage/SearchPage.search.filter.quantity.jsx
  src/app/SearchPage/SearchPage.search.jsx
  src/app/SearchPage/styled/SearchPage.component.style.js
  src/app/SearchPage/styled/SearchPage.search.filter.period.style.js
  src/app/SearchPage/styled/SearchPage.search.filter.style.js
Labels: enhancement

#51 feat: 각 카테고리 post 상세 보기 시 api 호출
  src/App.jsx
  src/app/MainPage/MainPage.CategoryDetailPage.Item.jsx
  src/app/MainPage/MainPage.CategoryDetailPage.jsx
  src/app/MainPage/MainPage.main.CategoryList.Category.jsx
  src/app/MainPage/MainPage.main.CategoryList.jsx
  src/app/MainPage/styled/MainPage.CategoryDetailPage.Item.style.js
  src/app/MainPage/styled/MainPage.main.CategoryList.Category.style.js
  src/main.jsx
Labels: enhancement

#57 refactor: token 및 endpoint .env 파일 이동
  src/app/MainPage/MainPage.CategoryDetailPage.jsx
  src/client.js
Labels: enhancement

#58 feat: 모집하기 필터 모달 기능 추가
  src/app/RecruitmentPage/Recruitment.main.jsx
  src/app/RecruitmentPage/Recruitment.modal.Category.jsx
  src/app/RecruitmentPage/Recruitment.modal.Range.jsx
  src/app/RecruitmentPage/Recruitment.modal.jsx
  src/app/RecruitmentPage/styled/Recruitment.main.style.js
  src/app/RecruitmentPage/styled/Recruitment.modal.style.js
Labels: bug, enhancement

#59 feat: 모집하기 입력 정보 state로 관리
  src/app/RecruitmentPage/Recruitment.MyMap.jsx
  src/app/RecruitmentPage/Recruitment.TradingLocation.jsx
  src/app/RecruitmentPage/Recruitment.main.jsx
  src/app/RecruitmentPage/styled/Recruitment.TradingLocation.style.js
  src/app/RecruitmentPage/styled/Recruitment.main.style.js
Labels: enhancement

#60 feat: 모집하기 등록 api 기능 추가
  src/app/RecruitmentPage/Recruitment.main.jsx
Labels: enhancement

#61 feat: 메인페이지 api 호출
  src/app/MainPage/MainPage.main.CategoryList.Category.Item.jsx
  src/app/MainPage/MainPage.main.CategoryList.Category.jsx
  src/app/MainPage/styled/MainPage.main.CategoryList.Category.Item.style.js
Labels: enhancement

#66 feat: 아이콘 이미지 추가 및 모집하기 버그 수정
  public/MainPage/Bell.png
  public/RecruitmentPage/camera.png
  src/app/MainPage/MainPage.Alarm.jsx
  src/app/MainPage/MainPage.CategoryDetailPage.jsx
  src/app/MainPage/MainPage.main.jsx
  src/app/MainPage/styled/MainPage.CategoryDatailPage.style.js
  src/app/MainPage/styled/MainPage.main.style.js
  src/app/MyTownPage/MyTownPage.Map.jsx
  src/app/MyTownPage/MyTownPage.main.BottomWrapper.jsx
  src/app/MyTownPage/MyTownPage.main.jsx
  src/app/RecruitmentPage/Recruitment.TradingLocation.jsx
  src/app/RecruitmentPage/Recruitment.main.jsx
  src/app/RecruitmentPage/styled/Recruitment.TradingLocation.style.js
  src/app/RecruitmentPage/styled/Recruitment.main.style.js
Labels: bug, enhancement

#68 feat: 검색페이지 기능 구현
  src/app/SearchPage/SearchPage.main.jsx
  src/app/SearchPage/SearchPage.search.filter.category.jsx
  src/app/SearchPage/SearchPage.search.filter.period.jsx
  src/app/SearchPage/SearchPage.search.filter.price.jsx
  src/app/SearchPage/SearchPage.search.filter.quantity.jsx
  src/app/SearchPage/SearchPage.search.jsx
  src/app/SearchPage/styled/SearchPage.component.style.js
  src/app/SearchPage/styled/SearchPage.main.style.js
  src/app/SearchPage/styled/SearchPage.search.filter.period.style.js
Labels: enhancement

#69 feat: 상품페이지 기능 구현
  src/app/ProductPage/ProductPage.main.CancelModal.jsx
  src/app/ProductPage/ProductPage.main.completeModal.jsx
  src/app/ProductPage/ProductPage.main.imgModal.jsx
  src/app/ProductPage/ProductPage.main.info.jsx
  src/app/ProductPage/ProductPage.main.jsx
  src/app/ProductPage/ProductPage.main.quantityModal.jsx
  src/app/ProductPage/styled/ProductPage.main.imgModal.style.js
  src/app/ProductPage/styled/ProductPage.main.info.style.js
  src/app/ProductPage/styled/ProductPage.main.selectModalComponent.style.js
  src/app/ProductPage/styled/ProductPage.main.style.js
Labels: enhancement

#73 design: 로딩 중 캐릭터 이미지 추가
  public/LoadingPage/moamoa.png
Labels: enhancement

#74 feat: 알림 페이지 api 호출
  public/MainPage/cart.png
  public/MainPage/comment.png
  public/MainPage/speaker.png
  src/app/MainPage/MainPage.Alarm.AlarmWrapper.jsx
  src/app/MainPage/MainPage.Alarm.jsx
  src/app/MainPage/styled/MainPage.Alarm.style.js
Labels: enhancement

#79 feat: 공지사항 기능 구현
  public/NoticePage/delete.png
  public/NoticePage/pencil.png
  public/ProductPage/left_angle.png
  public/ProductPage/right_angle.png
  src/App.jsx
  src/app/NoticePage/NoticePage.notice.comment.jsx
  src/app/NoticePage/NoticePage.notice.jsx
  src/app/NoticePage/NoticePage.write.jsx
  src/app/NoticePage/styled/NoticePage.notice.comment.style.js
  src/app/NoticePage/styled/NoticePage.notice.style.js
  src/app/NoticePage/styled/NoticePage.write.style.js
  src/app/ProductPage/ProductPage.main.imgModal.jsx
  src/app/ProductPage/ProductPage.main.info.jsx
  src/app/ProductPage/ProductPage.main.info.notice.jsx
  src/app/ProductPage/ProductPage.main.jsx
  src/app/ProductPage/ProductPage.main.quantityModal.jsx
  src/app/ProductPage/styled/ProductPage.main.imgModal.style.js
  src/app/ProductPage/styled/ProductPage.main.info.style.js
  src/app/SearchPage/SearchPage.main.jsx
  src/app/SearchPage/SearchPage.search.jsx
Labels: enhancement

#80 Feat/77
  public/MenuNav/C_Icon_home.png
  public/MenuNav/C_Icon_mypage.png
  public/MenuNav/Icon_home.png
  public/MenuNav/Icon_mypage.png
  public/MenuNav/Icon_mytown.png
  public/MenuNav/Icon_plus.png
  public/MenuNav/Icon_search.png
  src/app/MenuNav/MenuNav.main.jsx
  src/app/MenuNav/styled/MenuNav.main.style.js
Labels: enhancement

#83 feat: 상품페이지, 공지사항 페이지 상태 변경에 따른 새로고침
  src/app/NoticePage/NoticePage.notice.jsx
  src/app/NoticePage/styled/NoticePage.notice.style.js
  src/app/ProductPage/ProductPage.main.CancelModal.jsx
  src/app/ProductPage/ProductPage.main.quantityModal.jsx
Labels: enhancement

#85 fix: 공지사항 페이지 버그 해결
  src/app/NoticePage/NoticePage.write.jsx
  src/app/NoticePage/styled/NoticePage.write.style.js
Labels: bug

#87 feat: 검색페이지 필터 초기화 버튼 구현
  src/app/SearchPage/SearchPage.search.jsx
Labels: enhancement

#88 feat: 모집하기 > 필터 기간 설정 날짜 받아오기
  src/app/MyTownPage/MyTownPage.main.BottomWrapper.jsx
  src/app/RecruitmentPage/Recruitment.main.jsx
  src/app/RecruitmentPage/Recruitment.modal.Period.jsx
  src/app/RecruitmentPage/Recruitment.modal.jsx
  src/app/RecruitmentPage/styled/Recruitment.modal.style.js
  src/app/SearchPage/styled/SearchPage.search.filter.style.js
Labels: enhancement

#93 feat: 네이버 소셜 로그인 연동 후 recoil로 accessToken 상태 관리 로직 구현
  package-lock.json
  package.json
  src/App.jsx
  src/app/LoginPage/LoginPage.main.AddressSetup.jsx
  src/app/LoginPage/LoginPage.main.BasicInformation.jsx
  src/app/LoginPage/LoginPage.main.MemberInfo.jsx
  src/app/LoginPage/LoginPage.main.Welcome.jsx
  src/app/LoginPage/LoginPage.main.jsx
  src/app/LoginPage/LoginPage.service.js
  src/app/LoginPage/styled/LoginPage.main.AddressSetup.style.js
  src/app/LoginPage/styled/LoginPage.main.BasicInformation.style.js
  src/app/MainPage/MainPage.main.CategoryList.Category.jsx
  src/app/MainPage/MainPage.main.jsx
  src/app/MyPage/MyPage.main.NickNamePage.jsx
  src/app/MyPage/MyPage.service.js
  src/app/MyPage/styled/MyPage.main.NickNamePage.style.js
  src/app/RecruitmentPage/Recruitment.MyMap.jsx
  src/app/RecruitmentPage/Recruitment.TradingLocation.jsx
  src/client.js
  src/libs/localStorage.js
  src/recoil/atoms/AuthAtom.js
Labels: enhancement

#100 Feat/90
  public/LoginPage/logo.png
  src/app/LoginPage/LoginPage.main.Welcome.jsx
  src/app/LoginPage/styled/LoginPage.main.Welcome.style.js
  src/app/MainPage/MainPage.Alarm.jsx
  src/app/MainPage/MainPage.CategoryDetailPage.jsx
  src/app/MainPage/MainPage.main.CategoryList.Category.jsx
  src/app/MainPage/MainPage.main.jsx
  src/app/MyTownPage/MyTownPage.Map.jsx
  src/app/NoticePage/NoticePage.notice.jsx
  src/app/NoticePage/NoticePage.write.jsx
  src/app/ProductPage/ProductPage.main.CancelModal.jsx
  src/app/ProductPage/ProductPage.main.ChangeStateModal.jsx
  src/app/ProductPage/ProductPage.main.jsx
  src/app/ProductPage/ProductPage.main.quantityModal.jsx
  src/app/ProductPage/styled/ProductPage.main.style.js
  src/app/RecruitmentPage/Recruitment.TradingLocation.jsx
  src/app/RecruitmentPage/Recruitment.main.jsx
  src/app/RecruitmentPage/styled/Recruitment.modal.style.js
  src/app/SearchPage/SearchPage.main.jsx
  src/app/SearchPage/SearchPage.search.jsx
Labels: enhancement

#95 fix: 검색페이지 필터 부분 css 수정
  src/app/RecruitmentPage/styled/Recruitment.modal.style.js
  src/app/SearchPage/SearchPage.search.jsx
  src/app/SearchPage/styled/SearchPage.search.filter.style.js
Labels: bug

#97 feat: 공지사항 페이지 뒤로가기 구현
  src/app/MainPage/MainPage.CategoryDetailPage.Item.jsx
  src/app/NoticePage/NoticePage.notice.jsx
Labels: enhancement

#92 feat: 공지사항 페이지 사용자 이미지 가져오기
  src/app/NoticePage/NoticePage.notice.comment.jsx
  src/app/NoticePage/NoticePage.notice.jsx
  src/app/NoticePage/styled/NoticePage.notice.comment.style.js
  src/app/NoticePage/styled/NoticePage.notice.style.js
Labels: enhancement
